package somes.selfImproving.codeforces.A;

/**
 * Created by anme on 15.10.18.
 */
public class Task1065 {
    public static void main(String[] args) {
        System.out.println(calculateMaxChocolates(10, 3, 1, 1));
        System.out.println(calculateMaxChocolates(1000000000, 1, 1000000000, 1));
    }

    private static long calculateMaxChocolates(long initMoney, long numberToBuyToHaveGift, long gift, long chocolatePrice) {
        long giftIncludedChocolates = initMoney/numberToBuyToHaveGift * numberToBuyToHaveGift;
        return giftIncludedChocolates
                + gift*giftIncludedChocolates/numberToBuyToHaveGift
                + (initMoney - giftIncludedChocolates*chocolatePrice)/chocolatePrice;

    }
}

/*
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS CLOUDS
    */